### ISSUE TITLE
Windows 8.1 issue - AltDrag seems to work only a portion of a window

### ISSUE THREAD

**Issue by grpmpk** [stefansundin/altdrag#7]
I have a Surface 1 Pro with Windows 8.1 installed with the latest updates.  For some reason, AltDrag has issues with Windows 8.1:
1) I can Alt+LeftClick and move the window so long as I am clicking the left side of the window, that is, as long as the mouse cursor was hovering over less than ~50% (very approximate) of the width of the window.  Seems to have the same issue too with the height:  I have to be clicking on the top side of the window.
2) Consequently, if I alt-drag beyond the approximate 50%, say the lower right hand of the window, drastic effects can be seen, e.g., the icons on the desktop would be dragged away from their position.

It's hard to explain by words and I don't have the means to record by video at the moment.  For the time being, is my description of the issue clear?  If not, please let me know so I can clarify.

**Comment by rog1039** [comment]
Thanks, worked for me too!

**Comment by sethbc** [comment]
Issue persists in Windows 10, but would note the fix works as well (I'm running two 4K monitors @ 150% scaling, so haven't tried different pixel densities).

**Comment by TopTenTiger** [comment]
Ahh finally. This workaround should be out there, not hidden in the issue tracker. Tell about it in the docs/installer? More and more people get 1440p+ screens now and altdrag cocks up if DPI-scaling isn't disabled.

**Comment by stefansundin** [comment]
It is mentioned on the website, but you are right of course, if I can't fix the problem for the next version, then I'll probably add a note in the installer. Sorry.

**Comment by LMLB** [comment]
[Tutorial: Writing High-DPI Win32 Applications](https://msdn.microsoft.com/en-us/library/dd464659.aspx)

**Comment by dmwyatt** [comment]
The recommended fix does not work on the latest version of Windows 10.  

For one thing, "Disable display scaling on high DPI displays" is no long an option.  There's new options.

![Windows 10 DPI DPI options for compatibility mode](http://i.imgur.com/YbXtmTn.png)

None of them seem to fix AltDrags behavior when you're running multiple monitors with different DPI settings.

**Comment by Tahutipai** [comment]
Note: as of 2017-August this program returns positive on 3/64 tests on virustotal.com - returns positive for "Win32.Trojan.WisdomEyes".  Any comments from author?

**Comment by stefansundin** [comment]
@Tahutipai I am not surprised, since AltDrag uses keyboard and mouse hooks (and `HookWindows`, disabled by default, does even more invasive stuff). Many antivirus manufacturer uses heuristics to try to detect programs that does suspicious things. However, heuristics can't tell you for sure if something is malicious.

Here's the two scans:
- https://virustotal.com/#/file/68f145aed758a51b638632c4b3fb61343827a72a7f96ef8f4fba64c117451a02/detection
- https://virustotal.com/#/file/c45f48cf4e7f00f63f3e236c0226242d38392eb8dc2c85e1f6bed578b68c08de/detection

In the second one you can clearly see that it is some kind of heuristics by the name, "W32.eHeur.Malware12". The first one just says "Win32.Trojan.WisdomEyes.16070401" which is less clear.

Anyway, the only thing I can say is that it's clearly bogus. Please compile it yourself if you are worried, there are instructions here: https://stefansundin.github.io/altdrag/doc/build.html

In any case, thanks for reporting it! If I get the time I might submit false positive reports to the antivirus vendors.

**Comment by roblarky** [comment]
Try adding this to the manifest:

`  <application xmlns="urn:schemas-microsoft-com:asm.v3">

    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware>
      
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">permonitorv2,permonitor</dpiAwareness>
      
    </windowsSettings>
  </application>`

**Comment by davebrny** [comment]
thanks @dmwyatt, i havnt been able to use altdrag since i got a surface book last year. such a simple fix!

**Comment by MattSturgeon** [comment]
I've tried the updated workaround in [this comment](https://github.com/stefansundin/altdrag/issues/7#issuecomment-314945425) however I'm still reproducing the issue.

This is my config:

![2018-12-20 20_18_04 - issue 7](https://user-images.githubusercontent.com/5046562/50311067-d4508700-049b-11e9-9a81-fafbe0889018.png)

I've been trying to set up a build environment so that I can try @roblarky's [suggestion](https://github.com/stefansundin/altdrag/issues/7#issuecomment-360673051) however its not been going very well! Don't really want to install a full cygwin when I already have WSL and two mingw installs (one came with git).

**Comment by softyoda** [comment]
Hi, i have a 16/9  3840*2160 screen in 125% windows scale and a 21/9 3840*1600 screen in 100% windows scale. The program have issues sometimes.

I don't know how to add to manifest (is it the altdrag.ini or something else ?) thanks.

**Comment by MattSturgeon** [comment]
@softyoda probably easiest to install the patched version I linked to in #99.

You can also see how the manifest is changed by looking at the diff on that PR, but you'll have to build the project yourself if you want to apply the changes yourself (hence why I recommend the prebuilt fixed download)

**Comment by krizajb** [comment]
Where does one find the prebuild fixed download @MattSturgeon? I am having two 4k screens, one using 250% scale and another 175%. Thank you.

**Comment by softyoda** [comment]
On my side, I stopped using the software because it doesn't work as it should, I had to restart the session to restore the proper functioning of the explorer.
And this even with the prebuild fixed download.

**Comment by krizajb** [comment]
Unfortunately this is my best bet so far. Every other option I've tried so far works even worse. I did experience the same issues you are describing with the latest stable build. None with the prebuild fixed, but I've only been using it for an hour :P
PS: Did you find any alternative that works without any issues for our case?

**Comment by MattSturgeon** [comment]
Have you seen the AutoHotKey scripts liked [here](https://github.com/stefansundin/altdrag/issues/76#issuecomment-473046271)? They behave similar to AltDrag but are implemented completely differently, so manage to avoid many of the hidpi scaling weirdness and some other bugs.

**Comment by sparebytes** [comment]
I just tested the AutoHotKey script with two monitors at different DPIs. Unfortunately windows resize to become larger whenever they touch the border of the two monitors.

**Comment by krizajb** [comment]
Same here, I've posted my end results [here](https://github.com/stefansundin/altdrag/issues/76#issuecomment-527025601)

**Comment by loligans** [comment]
Microsoft is working on extending the Windows 10 shell with an application called, Power Toys. I recommend everyone to upvote this issue so Microsoft prioritizes Alt-Drag and Alt Resizing.
https://github.com/microsoft/PowerToys/issues/269

**Comment by Remington012** [comment]
My Windows 10 instance is also scaled by 125%.  The dialogs in Windows 10 now [look like Matt's screenshots](https://github.com/stefansundin/altdrag/issues/7#issuecomment-449145872) above, but I needed to use the [settings from Gilles's post](https://github.com/stefansundin/altdrag/issues/43#issuecomment-457181283) to resolve the issue.

So happy to finally have a solution to this issue!

**Comment by rbdone** [comment]
These settings are working for me in Windows 10 May 2020 update (build 2004) with a 4k monitor

![image](https://user-images.githubusercontent.com/74532/89085401-701bc780-d34e-11ea-8daa-1644affd351e.png)

**Comment by RamonUnch** [comment]
For information I am keeping a fork of AltDrag alive here, where I fixed DPI related issues a while back, alongside other issues related to Window 10 and Windows 8.x, on which I extensively test it.

https://github.com/RamonUnch/AltDrag/releases/

Apparently the work on the power toy implementation stopped.

**Comment by bufferUnderrun** [comment]
@RamonUnch **your version is just perfect** and solve all issues that suffer the old altdrag version. I use your but hard to find it on google and how is your relation with the official project is not clear. The original project is still not update, maybe it's time to fly on your own, rename-it and YOLO !

**Comment by RamonUnch** [comment]
Thanks for your feedback @bufferUnderrun, I opened a new issue to  discuss a [New name for the project](https://github.com/RamonUnch/AltDrag/issues/63)

**Comment by vsrawat** [comment]
I confirm odd behavior of AltDrag for SAMSUNG 32 inch 4K Ultra HD Monitor LU32J590UQWXXL

I was previously on LG 18.5 inch 1360x768 monitor and AltDrag worked well for years on various OS.

This week I got this UHD monitor, no other change, and AltDrag seems to be completely broken on W8.1 and w10 both 64 bits. 

When I click my Altdrag activation setting, and my cursor jumps to some other open window, and doesn't move any window at all, and even leaves windows beyond the screen.

I have tried various control key combination but couldn't make it to work.

Display in w8.1 is set to 150% and I am satisfied with what I see so no point for going for a smaller size.

I landed to this thread from google search. it matched with my issue so posting confirmation here instead of opening new issue.

Thanks.

**Comment by vsrawat** [comment]
> #### Workaround
> 
>     1. Right-click on AltDrag.exe > Properties > Compatibility tab
> 
>     2. Check the box for "Disable display scaling on high DPI displays"
> 
>     3. Restart Alt-Drag
> 
> 
> Now Alt-Drag behaves correctly no matter where in the window I start dragging from, even at native resolution.

That solved everything on w8.1-64 bit in a jiffy. Good old Altdrag is back.

Thanks a gig.

**Comment by nenesekai** [comment]
On Windows 11 the text has changed a bit but it's the same.

Go to the properties > compatibility tab > change high DPI settings > override high DPI scaling behavior

Scaling performed by set to Application

![image](https://user-images.githubusercontent.com/66727875/141883397-282f791b-1f52-4ed8-96c5-4b389266ae04.png)

then it should work as expected :)

**Comment by woctezuma** [comment]
> For information I am keeping a fork of AltDrag alive here, where I fixed DPI related issues a while back, alongside other issues related to Window 10 and Windows 8.x, on which I extensively test it.
> 
> https://github.com/RamonUnch/AltDrag/releases/
> 
> Apparently the work on the power toy implementation stopped.

Very nice! Using your fork is *another* workaround. :)
The pro is that I would not have to change properties of the executable if I were to install it on another computer.

That being said, I experience the same conflict with VS Code when using either AltDrag or AltSnap:
- https://github.com/microsoft/vscode/issues/141238

Not sure if there would be a fix for that weird issue.

**Edit:** Fixed with: 🥳 
- https://github.com/RamonUnch/AltSnap/issues/126#issuecomment-967312947

**Comment by stuaxo** [comment]
@RamonUnch can we upstream your changes to here if @stefansundin is up for it ?

**Comment by RamonUnch** [comment]
We already had this discussion here: https://github.com/stefansundin/altdrag/issues/124
Now my fork was renamed to AltSanp and went such a distance from AltDrag that there is not much sense in merging it into the original AltDrag. I did submit a couple of pull requests to fix some annoying bugs on but Stefan is focused on other projects.
